### PR TITLE
Fixing patterns for ChatHispano.

### PR DESCRIPTION
**Pull request by iwalkalone69**
Host in ChatHispano Network allows -.

### CODE REVIEW

**Comment by elazar** [comment]
@iwalkalone69 Tests will have to be updated to pass before this can be merged.

**Comment by iwalkalone69** [comment]
Added more characters, updated tests (all passed) and added comment.

**Comment by elazar** [comment]
@iwalkalone69 You've replaced the test case for an invalid message with one that is now considered valid. A test case is still needed to ensure that invalid messages are handled correctly. I would also like to see another test case that shows why the addition of a `utf8_encode()` call is needed.

**Comment by svpernova09** [comment]
Resolved with #41

**Pull request closed without merging**
