### PR TITLE
Drop php 5 5 support

### LINKED ISSUE #43: Drop Support for PHP 5.5

### PR DESCRIPTION
**Pull request by elstamey**
this resolves #43 

@rocketpastsix, please review when you have a minute

### CODE REVIEW

**Comment by rocketpastsix** [comment]
Since you added 7.1 to travis, can you update the ```allow_failures``` to handle 7.1 as well since it is still in testing and not a full release yet?

**Comment by elstamey** [comment]
@rocketpastsix ping

**Comment by elstamey** [comment]
@rocketpastsix I'm pinging you again here.  :)

**Comment by rocketpastsix** [comment]
looks good! thanks :)

**Pull request merged**
