### PR TITLE
Add support for PROTOCTL command

### PR DESCRIPTION
**Pull request by Renegade334**

### CODE REVIEW

**Comment by elazar** [comment]
Can you add a test case for this change?

**Comment by Renegade334** [comment]
I considered this, but ended up ignoring it as:

* PROTOCTL is an outgoing command only, so parser validation is really neither here nor there.
* because of the non-standard syntax, the parser processes NAMESX as a "targets" parameter, which the test case would have to actively assert in order to pass. Asserting something that is not logically correct isn't very desirable.

**Comment by elazar** [comment]
PROTOCTL is outgoing from the client perspective, but not from the server perspective. I'm not discounting the possibility that a server implementation could be created using this parser.

While NAMESX may not be logically or, more specifically, semantically correct, the relevancy of the test is that the parser correctly parses the command and arguments; no more, no less.

All other commands are covered by test cases. I'm afraid I have to insist that this command not be an exception, non-standard or no.

**Comment by Renegade334** [comment]
I've inserted a dummy empty capture into the regex to suppress the target parsing, which probably represents the best of both worlds. Rebased.

**Comment by elazar** [comment]
That does indeed seem a reasonable compromise. Well done. Thank you very much for your contribution, cooperation, and persistence. :)

**Pull request merged**
