### PR TITLE
Allowing ~ character in nicks. It is allowed in some networks.

### PR DESCRIPTION
**Pull request by iwalkalone69**
In some networks, like ChatHispano (http://www.chathispano.com/), ~ character is allowed in nicks (not at the begginning) so it is not parsing well the messages with this nicks.

### CODE REVIEW

**Comment by elazar** [comment]
This PR should add a test case for parsing a nick with `~` included.

**Comment by iwalkalone69** [comment]
I've added 3 tests for NICK, PRIVMSG and MODE.

**Comment by elazar** [comment]
Looks good to me. @svpernova09 / @rocketpastsix ?

**Comment by svpernova09** [comment]
Just restarted The travis build to double check tests

**Comment by iwalkalone69** [comment]
Thank you so much :-)

**Comment by svpernova09** [comment]
Thanks for the PR. I just tagged version 2.3.0

**Comment by iwalkalone69** [comment]
Thanks.

**Pull request merged**
